import { Separator } from "../ui/separator";

export function Footer() {
  return (
    <footer style={{ backgroundColor: "#003D7A" }} className="text-white py-12 px-6">
      <div className="max-w-6xl mx-auto">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6 mb-8">
          <div>
            <div
              className="text-xl font-bold mb-1"
              style={{ color: "#C8A04A" }}
            >
              Khalifa University
            </div>
            <div className="text-sm text-blue-200">
              College of Medicine and Health Sciences (CMHS)
            </div>
          </div>
          <div className="text-center md:text-right">
            <p className="text-sm text-blue-200">
              BSc Clinical Nutrition and Dietetics
            </p>
            <p className="text-sm font-semibold" style={{ color: "#C8A04A" }}>
              SPMD Minor + Concentration · Fall 2027
            </p>
          </div>
        </div>

        <Separator className="bg-white/20 mb-8" />

        <div className="text-center">
          <p className="text-sm text-blue-100">
            Prepared by{" "}
            <span className="font-semibold text-white">Dr. Carlo Raj</span> ·
            Khalifa University CMHS · 2026-05-18 · ADEK-aligned
          </p>
          <p className="text-xs text-blue-300 mt-2">
            Document version: v5 ENHANCED · Pipeline: Wave 2 / A5 ·
            Generated by SPMD Roadmap Pipeline
          </p>
          <p className="text-xs text-blue-300/60 mt-1">
            SPMD 301-304 pending UGCC review · SPMD 305-308 proposed, syllabi
            not yet authored · Subject to ADEK and KU approval
          </p>
        </div>
      </div>
    </footer>
  );
}
